# Generated by Django 2.2.1 on 2019-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190505_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default/profile.png', upload_to='profile_image'),
        ),
    ]
