# Generated by Django 2.2.1 on 2019-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20190516_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(blank=True)),
                ('profile_img', models.ImageField(upload_to='tesing/blog')),
            ],
            options={
                'verbose_name': 'TestBlog',
                'verbose_name_plural': 'TestBlogs',
            },
        ),
    ]
