# Generated by Django 2.2.1 on 2019-05-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestBlog',
        ),
    ]
