# Generated by Django 2.2.1 on 2019-05-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leverandorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Leverandor',
                'verbose_name_plural': 'Leverandorer',
            },
        ),
        migrations.CreateModel(
            name='Matriell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_nr', models.IntegerField(blank=True, null=True, unique=True)),
                ('tittel', models.CharField(blank=True, max_length=64, unique=True)),
                ('info', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('leverandor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriell.Leverandorer')),
            ],
            options={
                'verbose_name': 'Matriell',
                'verbose_name_plural': 'Matriell',
            },
        ),
    ]
