# Generated by Django 2.2.1 on 2019-05-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobber',
            fields=[
                ('ordre_nr', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tittel', models.CharField(blank=True, max_length=64, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=256)),
                ('telefon_nr', models.CharField(blank=True, max_length=64)),
                ('beskrivelse', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ferdig', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jobb',
                'verbose_name_plural': 'Jobber',
            },
        ),
        migrations.CreateModel(
            name='JobbMatriell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antall', models.IntegerField(default=1)),
                ('transf', models.BooleanField(default=False)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobb.Jobber')),
                ('matriell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriell.Matriell')),
            ],
            options={
                'verbose_name': 'JobbMatriell',
                'verbose_name_plural': 'JobbMatriell',
            },
        ),
        migrations.AddField(
            model_name='jobber',
            name='matriell',
            field=models.ManyToManyField(blank=True, to='jobb.JobbMatriell'),
        ),
    ]
