# Generated by Django 2.2.1 on 2019-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobber',
            name='profile_picture',
            field=models.ImageField(default='default/jobb_profile.png', upload_to='jobb_profile_image'),
        ),
    ]
