# Generated by Django 2.2.1 on 2019-05-15 17:53

from django.db import migrations, models
import django.db.models.deletion
import jobb.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobb', '0002_jobber_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobbImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=jobb.models.get_jobb_image_filename, verbose_name='Image')),
                ('jobb', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobb.Jobber')),
            ],
            options={
                'verbose_name': 'JobbImage',
                'verbose_name_plural': 'JobbImages',
            },
        ),
    ]
