# Generated by Django 2.2.1 on 2019-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobb', '0003_jobbimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbimage',
            name='image',
            field=models.ImageField(upload_to='jobbimages', verbose_name='Image'),
        ),
    ]
