# Generated by Django 2.2.1 on 2019-05-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettimeliste',
            name='ordre_nr',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gettimeliste',
            name='timer',
            field=models.SmallIntegerField(null=True),
        ),
    ]
