# Generated by Django 2.2.1 on 2019-05-02 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelister', '0002_auto_20190502_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobber',
            fields=[
                ('ordre_nr', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('matriell', models.CharField(blank=True, max_length=256)),
                ('telefon_nr', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jobber',
                'verbose_name_plural': 'Jobber',
            },
        ),
        migrations.CreateModel(
            name='Timeliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_timer', models.DateField(blank=True, null=True)),
                ('timer', models.SmallIntegerField(null=True)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelister.Jobber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timeliste',
                'verbose_name_plural': 'timelister',
            },
        ),
        migrations.DeleteModel(
            name='GetTimeliste',
        ),
    ]
