# Generated by Django 2.2.1 on 2019-05-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0003_auto_20190502_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobber',
            options={'verbose_name': 'Jobb', 'verbose_name_plural': 'Jobber'},
        ),
        migrations.RenameField(
            model_name='jobber',
            old_name='description',
            new_name='beskrivelse',
        ),
        migrations.RenameField(
            model_name='jobber',
            old_name='title',
            new_name='tittel',
        ),
        migrations.RenameField(
            model_name='timeliste',
            old_name='date_timer',
            new_name='dato',
        ),
        migrations.RemoveField(
            model_name='jobber',
            name='matriell',
        ),
        migrations.AddField(
            model_name='jobber',
            name='adresse',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Matriell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_nr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('beskrivelse', models.CharField(blank=True, max_length=128)),
                ('Leverandor', models.CharField(blank=True, max_length=128)),
                ('jobb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelister.Jobber')),
            ],
            options={
                'verbose_name': 'Matriell',
                'verbose_name_plural': 'Matriell',
            },
        ),
    ]
