# Generated by Django 2.2.1 on 2019-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0004_auto_20190503_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobber',
            name='telefon_nr',
            field=models.CharField(blank=True, default=0, max_length=64),
            preserve_default=False,
        ),
    ]
