# Generated by Django 2.2.1 on 2019-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0005_auto_20190503_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriell',
            name='el_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
