# Generated by Django 2.2.1 on 2019-05-07 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0006_auto_20190503_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobber',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
