# Generated by Django 2.2.1 on 2019-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0008_auto_20190507_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matriell',
            new_name='JobbMatriell',
        ),
    ]
