# Generated by Django 2.2.1 on 2019-05-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0009_auto_20190508_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_nr', models.IntegerField(blank=True, null=True)),
                ('tittel', models.CharField(blank=True, max_length=64)),
                ('info', models.CharField(blank=True, max_length=256)),
                ('Leverandor', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Matriell',
                'verbose_name_plural': 'Matriell',
            },
        ),
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='Leverandor',
        ),
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='beskrivelse',
        ),
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='el_nr',
        ),
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='jobb',
        ),
        migrations.AddField(
            model_name='jobber',
            name='ferdig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobber',
            name='matriell',
            field=models.ManyToManyField(to='timelister.JobbMatriell'),
        ),
        migrations.AddField(
            model_name='jobbmatriell',
            name='matriell',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timelister.Matriell'),
            preserve_default=False,
        ),
    ]
