# Generated by Django 2.2.1 on 2019-05-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0010_auto_20190508_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobbmatriell',
            options={'verbose_name': 'JobbMatriell', 'verbose_name_plural': 'JobbMatriell'},
        ),
        migrations.AlterField(
            model_name='matriell',
            name='Leverandor',
            field=models.CharField(choices=[('undef', 'Undefined'), ('elko', 'Elko'), ('betek', 'Betek'), ('draka', 'Draka')], max_length=15),
        ),
    ]
