# Generated by Django 2.2.1 on 2019-05-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0011_auto_20190508_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leverandorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Leverandor',
                'verbose_name_plural': 'Leverandorer',
            },
        ),
        migrations.AddField(
            model_name='jobbmatriell',
            name='antall',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matriell',
            name='Leverandor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelister.Leverandorer'),
        ),
    ]
