# Generated by Django 2.2.1 on 2019-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0012_auto_20190509_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobber',
            name='matriell',
            field=models.ManyToManyField(blank=True, to='timelister.JobbMatriell'),
        ),
    ]
