# Generated by Django 2.2.1 on 2019-05-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0013_auto_20190509_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbmatriell',
            name='ferdig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobbmatriell',
            name='jobb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timelister.Jobber'),
            preserve_default=False,
        ),
    ]
