# Generated by Django 2.2.1 on 2019-05-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0015_remove_jobbmatriell_jobb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobber',
            name='matriell',
        ),
    ]
