# Generated by Django 2.2.1 on 2019-05-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0017_auto_20190509_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='jobb',
        ),
    ]
