# Generated by Django 2.2.1 on 2019-05-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0018_remove_jobbmatriell_jobb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriell',
            old_name='Leverandor',
            new_name='leverandor',
        ),
    ]
