# Generated by Django 2.2.1 on 2019-05-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0019_auto_20190509_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbmatriell',
            name='jobb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timelister.Jobber'),
        ),
    ]
