# Generated by Django 2.2.1 on 2019-05-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0020_jobbmatriell_jobb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriell',
            name='leverandor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelister.Leverandorer'),
        ),
    ]
