# Generated by Django 2.2.1 on 2019-05-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0021_auto_20190510_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobbmatriell',
            old_name='ferdig',
            new_name='transf',
        ),
        migrations.AlterField(
            model_name='jobbmatriell',
            name='jobb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelister.Jobber'),
        ),
    ]
