# Generated by Django 2.2.1 on 2019-05-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0022_auto_20190510_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobber',
            name='tittel',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='matriell',
            name='el_nr',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='matriell',
            name='tittel',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
