# Generated by Django 2.2.1 on 2019-05-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0023_auto_20190510_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriell',
            name='leverandor',
        ),
        migrations.AlterField(
            model_name='jobbmatriell',
            name='matriell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriell.Matriell'),
        ),
        migrations.DeleteModel(
            name='Leverandorer',
        ),
        migrations.DeleteModel(
            name='Matriell',
        ),
    ]
