# Generated by Django 2.2.1 on 2019-05-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelister', '0024_auto_20190512_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='jobb',
        ),
        migrations.RemoveField(
            model_name='jobbmatriell',
            name='matriell',
        ),
        migrations.AlterField(
            model_name='timeliste',
            name='jobb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobb.Jobber'),
        ),
        migrations.DeleteModel(
            name='Jobber',
        ),
        migrations.DeleteModel(
            name='JobbMatriell',
        ),
    ]
